In [1]:
import numpy as np
import pandas as pd

In [2]:
from datetime import datetime
from datetime import timedelta

# 11.1 types and tools of date and time data

In [3]:
now = datetime.now()

In [4]:
now

datetime.datetime(2025, 11, 27, 22, 57, 58, 416541)

In [5]:
now.year, now.month, now.day

(2025, 11, 27)

In [6]:
delta = datetime(2011, 1, 7) - datetime(2008, 6, 24, 8,15)

In [7]:
delta

datetime.timedelta(days=926, seconds=56700)

In [8]:
delta.days

926

In [9]:
delta.seconds

56700

In [10]:
start = datetime(2011, 1, 7)

In [11]:
start + timedelta(12)

datetime.datetime(2011, 1, 19, 0, 0)

In [12]:
start - 2 * timedelta(12)

datetime.datetime(2010, 12, 14, 0, 0)

In [13]:
stamp = datetime(2011, 1, 3)

In [14]:
str(stamp)

'2011-01-03 00:00:00'

In [15]:
stamp.strftime("%Y-%M-%d")

'2011-00-03'

In [16]:
value = "2011-01-03"

In [17]:
datetime.strptime(value, "%Y-%m-%d")

datetime.datetime(2011, 1, 3, 0, 0)

In [18]:
datestrs = ["7/6/2011", "8/6/2011"]

In [19]:
[datetime.strptime(x, "%m/%d/%Y") for x in datestrs]

[datetime.datetime(2011, 7, 6, 0, 0), datetime.datetime(2011, 8, 6, 0, 0)]

In [20]:
datestrs = ["2011-07-06 12:00:00", "2011-08-06 00:00:00"]

In [21]:
pd.to_datetime(datestrs)

DatetimeIndex(['2011-07-06 12:00:00', '2011-08-06 00:00:00'], dtype='datetime64[ns]', freq=None)

In [22]:
idx = pd.to_datetime(datestrs + [None])

In [23]:
idx

DatetimeIndex(['2011-07-06 12:00:00', '2011-08-06 00:00:00', 'NaT'], dtype='datetime64[ns]', freq=None)

In [24]:
idx[2]

NaT

In [25]:
pd.isna(idx)

array([False, False,  True])

# 11.2 basic knowledge of time series

In [26]:
dates = [datetime(2011, 1, 2), datetime(2011, 1, 5),
         datetime(2011, 1, 7), datetime(2011, 1, 8),
         datetime(2011, 1, 10), datetime(2011, 1, 12)]

In [27]:
ts = pd.Series(np.random.standard_normal(6), index=dates)

In [28]:
ts

2011-01-02    0.896451
2011-01-05    0.392169
2011-01-07    0.479198
2011-01-08   -0.835518
2011-01-10   -0.472047
2011-01-12    0.742820
dtype: float64

In [29]:
ts.index

DatetimeIndex(['2011-01-02', '2011-01-05', '2011-01-07', '2011-01-08',
               '2011-01-10', '2011-01-12'],
              dtype='datetime64[ns]', freq=None)

In [30]:
ts +ts[::2]

2011-01-02    1.792902
2011-01-05         NaN
2011-01-07    0.958395
2011-01-08         NaN
2011-01-10   -0.944093
2011-01-12         NaN
dtype: float64

In [31]:
ts.index.dtype

dtype('<M8[ns]')

In [32]:
stamp = ts.index[0]

In [33]:
stamp

Timestamp('2011-01-02 00:00:00')

# 11.2.1 index select subset construction

In [34]:
stamp = ts.index[2]

In [35]:
ts[stamp]

np.float64(0.479197542570693)

In [36]:
ts["2011-01-10"]

np.float64(-0.4720467265190769)

In [37]:
longer_ts = pd.Series(np.random.standard_normal(1000),
                      index=pd.date_range("2000-01-01", periods=1000))

In [38]:
longer_ts

2000-01-01    0.614432
2000-01-02   -0.283337
2000-01-03    0.390954
2000-01-04   -0.318437
2000-01-05    0.938494
                ...
2002-09-22   -0.014015
2002-09-23   -2.150207
2002-09-24    0.162403
2002-09-25   -0.122347
2002-09-26    1.155841
Freq: D, Length: 1000, dtype: float64

In [39]:
longer_ts["2001"]

2001-01-01    0.459806
2001-01-02   -1.868321
2001-01-03    0.312425
2001-01-04    0.908186
2001-01-05   -0.970926
                ...
2001-12-27   -0.003316
2001-12-28    1.028842
2001-12-29   -0.298293
2001-12-30   -1.834696
2001-12-31   -1.145734
Freq: D, Length: 365, dtype: float64

In [40]:
longer_ts["2001-05"]

2001-05-01    1.152031
2001-05-02    0.123884
2001-05-03   -0.820007
2001-05-04   -1.099892
2001-05-05   -0.135450
2001-05-06    0.352690
2001-05-07    0.664094
2001-05-08    1.329382
2001-05-09    0.981462
2001-05-10   -0.708138
2001-05-11   -0.376161
2001-05-12   -0.587798
2001-05-13   -1.413188
2001-05-14   -0.242979
2001-05-15    0.298819
2001-05-16    0.999171
2001-05-17   -0.317130
2001-05-18    1.764153
2001-05-19    0.523460
2001-05-20   -1.306773
2001-05-21    1.391172
2001-05-22   -0.794303
2001-05-23   -0.567691
2001-05-24   -0.096321
2001-05-25    0.036762
2001-05-26    0.609787
2001-05-27    0.706748
2001-05-28    0.145288
2001-05-29   -1.085764
2001-05-30   -0.935875
2001-05-31    0.592020
Freq: D, dtype: float64

In [41]:
ts[datetime(2011, 1, 7):]

2011-01-07    0.479198
2011-01-08   -0.835518
2011-01-10   -0.472047
2011-01-12    0.742820
dtype: float64

In [42]:
ts[datetime(2011, 1, 7):datetime(2011, 1, 10)]

2011-01-07    0.479198
2011-01-08   -0.835518
2011-01-10   -0.472047
dtype: float64

In [43]:
ts

2011-01-02    0.896451
2011-01-05    0.392169
2011-01-07    0.479198
2011-01-08   -0.835518
2011-01-10   -0.472047
2011-01-12    0.742820
dtype: float64

In [44]:
ts["2011-01-06":"2011-01-11"]

2011-01-07    0.479198
2011-01-08   -0.835518
2011-01-10   -0.472047
dtype: float64

In [45]:
ts.truncate(after="2011-01-09")

2011-01-02    0.896451
2011-01-05    0.392169
2011-01-07    0.479198
2011-01-08   -0.835518
dtype: float64

In [46]:
dates = pd.date_range("2000-01-01", periods=100, freq="W-WED")

In [47]:
long_df = pd.DataFrame(np.random.standard_normal((100,4)),
                       index=dates,
                       columns=["Colorado", "Texas",
                                "New York", "Ohio"])

In [48]:
long_df.loc["2001-05"]

            Colorado     Texas  New York      Ohio
2001-05-02  0.742966 -1.653542 -0.380563  0.996330
2001-05-09 -1.046851 -1.702170 -0.077089  0.063257
2001-05-16 -2.072288 -1.238279 -0.070954  1.268729
2001-05-23 -0.915861 -1.791139  1.058960 -2.996582
2001-05-30 -0.227950 -0.520292  0.285469  0.038844

# 11.2.2 time series with duplicate indexes

In [49]:
dates = pd.DatetimeIndex(["2000-01-01", "2000-01-02", "2000-01-02",
                      "2000-01-02", "2000-01-03"])

In [50]:
dup_ts = pd.Series(np.arange(5), index=dates)

In [51]:
dup_ts

2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-02    3
2000-01-03    4
dtype: int64

In [52]:
dup_ts.index.is_unique

False

In [53]:
dup_ts["2000-01-03"]

np.int64(4)

In [54]:
dup_ts["2000-01-02"]

2000-01-02    1
2000-01-02    2
2000-01-02    3
dtype: int64

In [55]:
grouped = dup_ts.groupby(level=0)

In [56]:
grouped.mean()

2000-01-01    0.0
2000-01-02    2.0
2000-01-03    4.0
dtype: float64

In [57]:
grouped.count()

2000-01-01    1
2000-01-02    3
2000-01-03    1
dtype: int64

# 11.3 Range,frequency,and shift of dates

In [58]:
ts

2011-01-02    0.896451
2011-01-05    0.392169
2011-01-07    0.479198
2011-01-08   -0.835518
2011-01-10   -0.472047
2011-01-12    0.742820
dtype: float64

In [59]:
resampler = ts.resample("D")

In [60]:
resampler

# 11.3.1 Generate date range

In [61]:
index = pd.date_range("2012-04-01", "2012-06-01")

In [62]:
index

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
               '2012-04-13', '2012-04-14', '2012-04-15', '2012-04-16',
               '2012-04-17', '2012-04-18', '2012-04-19', '2012-04-20',
               '2012-04-21', '2012-04-22', '2012-04-23', '2012-04-24',
               '2012-04-25', '2012-04-26', '2012-04-27', '2012-04-28',
               '2012-04-29', '2012-04-30', '2012-05-01', '2012-05-02',
               '2012-05-03', '2012-05-04', '2012-05-05', '2012-05-06',
               '2012-05-07', '2012-05-08', '2012-05-09', '2012-05-10',
               '2012-05-11', '2012-05-12', '2012-05-13', '2012-05-14',
               '2012-05-15', '2012-05-16', '2012-05-17', '2012-05-18',
               '2012-05-19', '2012-05-20', '2012-05-21', '2012-05-22',
               '2012-05-23', '2012-05-24', '2012-05-25', '2012-05-26',
               '2012-05-27', '2012-05-28', '2012-05-29', '2012-05-30',
               '2012-05-31', '2012-06-01'],
              dtype='datetime64[ns]', freq='D')

In [63]:
pd.date_range(start="2012-04-01", periods=20)

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
               '2012-04-13', '2012-04-14', '2012-04-15', '2012-04-16',
               '2012-04-17', '2012-04-18', '2012-04-19', '2012-04-20'],
              dtype='datetime64[ns]', freq='D')

In [64]:
pd.date_range(end="2012-06-01", periods=20)

DatetimeIndex(['2012-05-13', '2012-05-14', '2012-05-15', '2012-05-16',
               '2012-05-17', '2012-05-18', '2012-05-19', '2012-05-20',
               '2012-05-21', '2012-05-22', '2012-05-23', '2012-05-24',
               '2012-05-25', '2012-05-26', '2012-05-27', '2012-05-28',
               '2012-05-29', '2012-05-30', '2012-05-31', '2012-06-01'],
              dtype='datetime64[ns]', freq='D')

In [65]:
pd.date_range("2000-01-01", "2000-12-01", freq="BM")

/tmp/ipykernel_3803/3742551278.py:1: FutureWarning: 'BM' is deprecated and will be removed in a future version, please use 'BME' instead.
  pd.date_range("2000-01-01", "2000-12-01", freq="BM")

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-28',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31',
               '2000-09-29', '2000-10-31', '2000-11-30'],
              dtype='datetime64[ns]', freq='BME')

In [66]:
pd.date_range("2012-05-02 12:56:31", periods=5)

DatetimeIndex(['2012-05-02 12:56:31', '2012-05-03 12:56:31',
               '2012-05-04 12:56:31', '2012-05-05 12:56:31',
               '2012-05-06 12:56:31'],
              dtype='datetime64[ns]', freq='D')

In [67]:
pd.date_range("2012-05-02 12:56:31", periods=5, normalize=True)

DatetimeIndex(['2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
               '2012-05-06'],
              dtype='datetime64[ns]', freq='D')

# 11.3.2 Frequency and date offset

In [68]:
from pandas.tseries.offsets import Hour, Minute

In [69]:
hour = Hour()

In [70]:
hour

In [71]:
four_hours = Hour(4)

In [72]:
four_hours

In [73]:
pd.date_range("2000-01-01", "2000-01-03 23:59", freq="4H")

/tmp/ipykernel_3803/3449897904.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range("2000-01-01", "2000-01-03 23:59", freq="4H")

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 04:00:00',
               '2000-01-01 08:00:00', '2000-01-01 12:00:00',
               '2000-01-01 16:00:00', '2000-01-01 20:00:00',
               '2000-01-02 00:00:00', '2000-01-02 04:00:00',
               '2000-01-02 08:00:00', '2000-01-02 12:00:00',
               '2000-01-02 16:00:00', '2000-01-02 20:00:00',
               '2000-01-03 00:00:00', '2000-01-03 04:00:00',
               '2000-01-03 08:00:00', '2000-01-03 12:00:00',
               '2000-01-03 16:00:00', '2000-01-03 20:00:00'],
              dtype='datetime64[ns]', freq='4h')

In [74]:
Hour(2) + Minute(30)

In [75]:
pd.date_range("2000-01-01", periods=10, freq="1h30min")

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 01:30:00',
               '2000-01-01 03:00:00', '2000-01-01 04:30:00',
               '2000-01-01 06:00:00', '2000-01-01 07:30:00',
               '2000-01-01 09:00:00', '2000-01-01 10:30:00',
               '2000-01-01 12:00:00', '2000-01-01 13:30:00'],
              dtype='datetime64[ns]', freq='90min')

In [76]:
monthly_dates = pd.date_range("2012-01-01", "2012-09-01", freq="WOM-3FRI")

In [77]:
list(monthly_dates)

[Timestamp('2012-01-20 00:00:00'),
 Timestamp('2012-02-17 00:00:00'),
 Timestamp('2012-03-16 00:00:00'),
 Timestamp('2012-04-20 00:00:00'),
 Timestamp('2012-05-18 00:00:00'),
 Timestamp('2012-06-15 00:00:00'),
 Timestamp('2012-07-20 00:00:00'),
 Timestamp('2012-08-17 00:00:00')]

# 11.3.3 Shift the leading and lagging data

In [78]:
ts = pd.Series(np.random.standard_normal(4),
               index=pd.date_range("2000-01-01", periods=4, freq="M"))

/tmp/ipykernel_3803/2098005487.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  index=pd.date_range("2000-01-01", periods=4, freq="M"))

In [79]:
ts

2000-01-31    0.958048
2000-02-29   -1.178220
2000-03-31   -1.677967
2000-04-30    1.637331
Freq: ME, dtype: float64

In [80]:
ts.shift(2)

2000-01-31         NaN
2000-02-29         NaN
2000-03-31    0.958048
2000-04-30   -1.178220
Freq: ME, dtype: float64

In [81]:
ts.shift(-2)

2000-01-31   -1.677967
2000-02-29    1.637331
2000-03-31         NaN
2000-04-30         NaN
Freq: ME, dtype: float64

In [82]:
ts.shift(2, freq="M")

/tmp/ipykernel_3803/903147437.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts.shift(2, freq="M")

2000-03-31    0.958048
2000-04-30   -1.178220
2000-05-31   -1.677967
2000-06-30    1.637331
Freq: ME, dtype: float64

In [83]:
ts.shift(2, freq="ME")

2000-03-31    0.958048
2000-04-30   -1.178220
2000-05-31   -1.677967
2000-06-30    1.637331
Freq: ME, dtype: float64

In [84]:
ts.shift(3, freq="D")

2000-02-03    0.958048
2000-03-03   -1.178220
2000-04-03   -1.677967
2000-05-03    1.637331
dtype: float64

In [85]:
ts.shift(1, freq="90T")

/tmp/ipykernel_3803/584021106.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  ts.shift(1, freq="90T")

2000-01-31 01:30:00    0.958048
2000-02-29 01:30:00   -1.178220
2000-03-31 01:30:00   -1.677967
2000-04-30 01:30:00    1.637331
dtype: float64

In [86]:
ts.shift(1, freq="90min")

2000-01-31 01:30:00    0.958048
2000-02-29 01:30:00   -1.178220
2000-03-31 01:30:00   -1.677967
2000-04-30 01:30:00    1.637331
dtype: float64

In [87]:
from pandas.tseries.offsets import Day, MonthEnd

In [88]:
now = datetime(2011, 11, 17)

In [89]:
now + 3 * Day()

Timestamp('2011-11-20 00:00:00')

In [90]:
now + MonthEnd()

Timestamp('2011-11-30 00:00:00')

In [91]:
now + MonthEnd(2)

Timestamp('2011-12-31 00:00:00')

In [92]:
offset = MonthEnd()

In [93]:
offset.rollforward(now)

Timestamp('2011-11-30 00:00:00')

In [94]:
offset.rollback(now)

Timestamp('2011-10-31 00:00:00')

In [95]:
ts = pd.Series(np.random.standard_normal(20),
               index=pd.date_range("2000-01-15", periods=20, freq="4D"))

In [96]:
ts

2000-01-15    0.044361
2000-01-19    2.022957
2000-01-23    0.627567
2000-01-27    0.415102
2000-01-31    0.949803
2000-02-04   -0.104326
2000-02-08    0.829467
2000-02-12    2.444842
2000-02-16   -0.200860
2000-02-20   -0.715595
2000-02-24   -0.373711
2000-02-28   -0.572483
2000-03-03   -0.300423
2000-03-07    0.195835
2000-03-11    0.751060
2000-03-15    0.862092
2000-03-19   -0.585418
2000-03-23    0.670986
2000-03-27    0.131693
2000-03-31   -0.567010
Freq: 4D, dtype: float64

In [97]:
ts.groupby(MonthEnd().rollforward).mean()

2000-01-31    0.811958
2000-02-29    0.186762
2000-03-31    0.144852
dtype: float64

In [98]:
ts.resample("ME").mean()

2000-01-31    0.811958
2000-02-29    0.186762
2000-03-31    0.144852
Freq: ME, dtype: float64

# 11.4 Time zone process

In [99]:
import pytz

In [100]:
pytz.common_timezones[-5:]

['US/Eastern', 'US/Hawaii', 'US/Mountain', 'US/Pacific', 'UTC']

In [101]:
tz = pytz.timezone("America/New_York")

In [102]:
tz

# 11.4.1 Localization and Conversion of Time zones

In [103]:
dates = pd.date_range("2012-03-09 09:30", periods=6)

In [104]:
ts = pd.Series(np.random.standard_normal(len(dates)), index=dates)

In [105]:
ts

2012-03-09 09:30:00   -0.675375
2012-03-10 09:30:00   -0.064931
2012-03-11 09:30:00   -1.845022
2012-03-12 09:30:00   -0.150172
2012-03-13 09:30:00    0.614893
2012-03-14 09:30:00   -0.758630
Freq: D, dtype: float64

In [106]:
print(ts.index.tz)

None

In [107]:
pd.date_range("2012-03-09 09:30", periods=10, tz="UTC")

DatetimeIndex(['2012-03-09 09:30:00+00:00', '2012-03-10 09:30:00+00:00',
               '2012-03-11 09:30:00+00:00', '2012-03-12 09:30:00+00:00',
               '2012-03-13 09:30:00+00:00', '2012-03-14 09:30:00+00:00',
               '2012-03-15 09:30:00+00:00', '2012-03-16 09:30:00+00:00',
               '2012-03-17 09:30:00+00:00', '2012-03-18 09:30:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='D')

In [108]:
ts

2012-03-09 09:30:00   -0.675375
2012-03-10 09:30:00   -0.064931
2012-03-11 09:30:00   -1.845022
2012-03-12 09:30:00   -0.150172
2012-03-13 09:30:00    0.614893
2012-03-14 09:30:00   -0.758630
Freq: D, dtype: float64

In [109]:
ts_utc = ts.tz_localize("UTC")

In [110]:
ts_utc

2012-03-09 09:30:00+00:00   -0.675375
2012-03-10 09:30:00+00:00   -0.064931
2012-03-11 09:30:00+00:00   -1.845022
2012-03-12 09:30:00+00:00   -0.150172
2012-03-13 09:30:00+00:00    0.614893
2012-03-14 09:30:00+00:00   -0.758630
Freq: D, dtype: float64

In [111]:
ts_utc.index

DatetimeIndex(['2012-03-09 09:30:00+00:00', '2012-03-10 09:30:00+00:00',
               '2012-03-11 09:30:00+00:00', '2012-03-12 09:30:00+00:00',
               '2012-03-13 09:30:00+00:00', '2012-03-14 09:30:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='D')

In [112]:
ts_utc.tz_convert("America/New_York")

2012-03-09 04:30:00-05:00   -0.675375
2012-03-10 04:30:00-05:00   -0.064931
2012-03-11 05:30:00-04:00   -1.845022
2012-03-12 05:30:00-04:00   -0.150172
2012-03-13 05:30:00-04:00    0.614893
2012-03-14 05:30:00-04:00   -0.758630
Freq: D, dtype: float64

In [113]:
ts_eastern = ts.tz_localize("America/New_York")

In [114]:
ts_eastern.tz_convert("UTC")

2012-03-09 14:30:00+00:00   -0.675375
2012-03-10 14:30:00+00:00   -0.064931
2012-03-11 13:30:00+00:00   -1.845022
2012-03-12 13:30:00+00:00   -0.150172
2012-03-13 13:30:00+00:00    0.614893
2012-03-14 13:30:00+00:00   -0.758630
dtype: float64

In [115]:
ts_eastern.tz_convert("Europe/Berlin")

2012-03-09 15:30:00+01:00   -0.675375
2012-03-10 15:30:00+01:00   -0.064931
2012-03-11 14:30:00+01:00   -1.845022
2012-03-12 14:30:00+01:00   -0.150172
2012-03-13 14:30:00+01:00    0.614893
2012-03-14 14:30:00+01:00   -0.758630
dtype: float64

In [116]:
ts.index.tz_localize("Asia/Shanghai")

DatetimeIndex(['2012-03-09 09:30:00+08:00', '2012-03-10 09:30:00+08:00',
               '2012-03-11 09:30:00+08:00', '2012-03-12 09:30:00+08:00',
               '2012-03-13 09:30:00+08:00', '2012-03-14 09:30:00+08:00'],
              dtype='datetime64[ns, Asia/Shanghai]', freq=None)

# 11.4.2 Operation on time zone type timestamp objects

In [117]:
stamp = pd.Timestamp("2011-03-12 04:00")

In [118]:
stamp_utc = stamp.tz_localize("utc")

In [119]:
stamp_utc.tz_convert("America/New_York")

Timestamp('2011-03-11 23:00:00-0500', tz='America/New_York')

In [120]:
stamp_moscow = pd.Timestamp("2011-03-12 04:00", tz="Europe/Moscow")

In [121]:
stamp_moscow

Timestamp('2011-03-12 04:00:00+0300', tz='Europe/Moscow')

In [122]:
stamp_utc.value

1299902400000000000

In [123]:
stamp_utc.tz_convert("America/New_York").value

1299902400000000000

In [124]:
stamp = pd.Timestamp("2012-03-11 01:30", tz="US/Eastern")

In [125]:
stamp

Timestamp('2012-03-11 01:30:00-0500', tz='US/Eastern')

In [126]:
stamp + Hour()

Timestamp('2012-03-11 03:30:00-0400', tz='US/Eastern')

In [127]:
stamp = pd.Timestamp("2012-11-04 00:30", tz="US/Eastern")

In [128]:
stamp

Timestamp('2012-11-04 00:30:00-0400', tz='US/Eastern')

In [129]:
stamp + 2 * Hour()

Timestamp('2012-11-04 01:30:00-0500', tz='US/Eastern')

# 11.4.3 Operations between differrent time zones

In [130]:
dates = pd.date_range("2012-03-07 09:30", periods=10, freq="B")

In [131]:
ts = pd.Series(np.random.standard_normal(len(dates)), index=dates)

In [132]:
ts

2012-03-07 09:30:00    1.532798
2012-03-08 09:30:00   -0.073201
2012-03-09 09:30:00    0.060112
2012-03-12 09:30:00   -1.605670
2012-03-13 09:30:00    1.176149
2012-03-14 09:30:00    0.797907
2012-03-15 09:30:00   -0.588046
2012-03-16 09:30:00    1.162577
2012-03-19 09:30:00   -1.340366
2012-03-20 09:30:00   -0.425456
Freq: B, dtype: float64

In [133]:
ts1 = ts[:7].tz_localize("Europe/London")

In [134]:
ts2 = ts1[2:].tz_convert("Europe/Moscow")

In [135]:
result = ts1 + ts2

In [136]:
result.index

DatetimeIndex(['2012-03-07 09:30:00+00:00', '2012-03-08 09:30:00+00:00',
               '2012-03-09 09:30:00+00:00', '2012-03-12 09:30:00+00:00',
               '2012-03-13 09:30:00+00:00', '2012-03-14 09:30:00+00:00',
               '2012-03-15 09:30:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

# 11.5 Cycle and its arithmetic operations

In [137]:
p = pd.Period("2011", freq="A-DEC")

/tmp/ipykernel_3803/3436265626.py:1: FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
  p = pd.Period("2011", freq="A-DEC")

In [138]:
p

Period('2011', 'Y-DEC')

In [139]:
p + 5

Period('2016', 'Y-DEC')

In [140]:
p - 2

Period('2009', 'Y-DEC')

In [141]:
pd.Period("2014", freq="A-DEC") - p

/tmp/ipykernel_3803/3816979827.py:1: FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
  pd.Period("2014", freq="A-DEC") - p

In [142]:
periods = pd.period_range("2000-01-01", "2000-06-30", freq="M")

In [143]:
periods

PeriodIndex(['2000-01', '2000-02', '2000-03', '2000-04', '2000-05', '2000-06'], dtype='period[M]')

In [144]:
pd.Series(np.random.standard_normal(6), index=periods)

2000-01   -0.119141
2000-02    0.881448
2000-03    0.904720
2000-04    0.406796
2000-05   -0.924437
2000-06    0.763818
Freq: M, dtype: float64

In [145]:
values = ["2001Q3", "2002Q2", "2003Q1"]

In [146]:
index = pd.PeriodIndex(values, freq="Q-DEC")

In [147]:
index

PeriodIndex(['2001Q3', '2002Q2', '2003Q1'], dtype='period[Q-DEC]')

# 11.5.1 Frequency conversion of cycles

In [148]:
p = pd.Period("2011", freq="A-DEC")

/tmp/ipykernel_3803/3436265626.py:1: FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
  p = pd.Period("2011", freq="A-DEC")

In [149]:
p

Period('2011', 'Y-DEC')

In [150]:
p.asfreq("M", how="start")

Period('2011-01', 'M')

In [151]:
p.asfreq("M", how="end")

Period('2011-12', 'M')

In [152]:
p.asfreq("M")

Period('2011-12', 'M')

In [153]:
p = pd.Period("2011", freq="A-JUN")

/tmp/ipykernel_3803/3595438442.py:1: FutureWarning: 'A-JUN' is deprecated and will be removed in a future version, please use 'Y-JUN' instead.
  p = pd.Period("2011", freq="A-JUN")

In [154]:
p

Period('2011', 'Y-JUN')

In [155]:
p.asfreq("M", how="start")

Period('2010-07', 'M')

In [156]:
p.asfreq("M", how="end")

Period('2011-06', 'M')

In [157]:
p = pd.Period("Aug-2011", "M")

In [158]:
p.asfreq("A-JUN")

/tmp/ipykernel_3803/1565973874.py:1: FutureWarning: 'A-JUN' is deprecated and will be removed in a future version, please use 'Y-JUN' instead.
  p.asfreq("A-JUN")

Period('2012', 'Y-JUN')

In [159]:
periods = pd.period_range("2006", "2009", freq="A-DEC")

/tmp/ipykernel_3803/3066967862.py:1: FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
  periods = pd.period_range("2006", "2009", freq="A-DEC")

In [160]:
ts = pd.Series(np.random.standard_normal(len(periods)), index=periods)

In [161]:
ts

2006    0.136455
2007   -0.634764
2008   -0.743524
2009    1.023104
Freq: Y-DEC, dtype: float64

In [162]:
ts.asfreq("M", how="start")

2006-01    0.136455
2007-01   -0.634764
2008-01   -0.743524
2009-01    1.023104
Freq: M, dtype: float64

In [163]:
ts.asfreq("B", how="end")

/tmp/ipykernel_3803/2984082239.py:1: FutureWarning: PeriodDtype[B] is deprecated and will be removed in a future version. Use a DatetimeIndex with freq='B' instead
  ts.asfreq("B", how="end")

2006-12-29    0.136455
2007-12-31   -0.634764
2008-12-31   -0.743524
2009-12-31    1.023104
Freq: B, dtype: float64

# 11.5.2 Quarterly cycle frequency

In [164]:
p = pd.Period("2012Q4", freq="Q-JAN")

In [165]:
p

Period('2012Q4', 'Q-JAN')

In [166]:
p.asfreq("D", how="start")

Period('2011-11-01', 'D')

In [167]:
p.asfreq("D", how="end")

Period('2012-01-31', 'D')

In [168]:
p4pm = (p.asfreq("B", how="end") - 1).asfreq("T", how="start") + 16 * 60

/tmp/ipykernel_3803/2204560885.py:1: FutureWarning: Period with BDay freq is deprecated and will be removed in a future version. Use a DatetimeIndex with BDay freq instead.
  p4pm = (p.asfreq("B", how="end") - 1).asfreq("T", how="start") + 16 * 60
/tmp/ipykernel_3803/2204560885.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  p4pm = (p.asfreq("B", how="end") - 1).asfreq("T", how="start") + 16 * 60

In [169]:
p4pm

Period('2012-01-30 16:00', 'min')

In [170]:
p4pm.to_timestamp()

Timestamp('2012-01-30 16:00:00')

In [171]:
periods = pd.period_range("2011Q3", "2012Q4", freq="Q-JAN")

In [172]:
ts = pd.Series(np.arange(len(periods)), index=periods)

In [173]:
ts

2011Q3    0
2011Q4    1
2012Q1    2
2012Q2    3
2012Q3    4
2012Q4    5
Freq: Q-JAN, dtype: int64

In [174]:
new_periods = (periods.asfreq("B", "end") - 1).asfreq("H", "start") + 16

/tmp/ipykernel_3803/3213338784.py:1: FutureWarning: PeriodDtype[B] is deprecated and will be removed in a future version. Use a DatetimeIndex with freq='B' instead
  new_periods = (periods.asfreq("B", "end") - 1).asfreq("H", "start") + 16
/tmp/ipykernel_3803/3213338784.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  new_periods = (periods.asfreq("B", "end") - 1).asfreq("H", "start") + 16

In [175]:
ts.index = new_periods.to_timestamp()

In [176]:
ts

2010-10-28 16:00:00    0
2011-01-28 16:00:00    1
2011-04-28 16:00:00    2
2011-07-28 16:00:00    3
2011-10-28 16:00:00    4
2012-01-30 16:00:00    5
dtype: int64

# 11.5.3 Conversion between timestamp and period

In [177]:
dates = pd.date_range("2000-01-01", periods=3, freq="M")

/tmp/ipykernel_3803/1909817033.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("2000-01-01", periods=3, freq="M")

In [178]:
ts = pd.Series(np.random.standard_normal(3), index=dates)

In [179]:
ts

2000-01-31    0.758890
2000-02-29   -0.437919
2000-03-31    1.162288
Freq: ME, dtype: float64

In [180]:
pts = ts.to_period()

In [181]:
pts

2000-01    0.758890
2000-02   -0.437919
2000-03    1.162288
Freq: M, dtype: float64

In [182]:
dates = pd.date_range("2000-01-29", periods=6)

In [183]:
ts2 = pd.Series(np.random.standard_normal(6), index=dates)

In [184]:
ts2

2000-01-29   -0.226446
2000-01-30    2.459283
2000-01-31   -1.356171
2000-02-01    0.744451
2000-02-02    1.182222
2000-02-03   -0.951160
Freq: D, dtype: float64

In [185]:
ts2.to_period("M")

2000-01   -0.226446
2000-01    2.459283
2000-01   -1.356171
2000-02    0.744451
2000-02    1.182222
2000-02   -0.951160
Freq: M, dtype: float64

In [186]:
pts = ts2.to_period()

In [187]:
pts

2000-01-29   -0.226446
2000-01-30    2.459283
2000-01-31   -1.356171
2000-02-01    0.744451
2000-02-02    1.182222
2000-02-03   -0.951160
Freq: D, dtype: float64

In [188]:
pts.to_timestamp(how="end")

2000-01-29 23:59:59.999999999   -0.226446
2000-01-30 23:59:59.999999999    2.459283
2000-01-31 23:59:59.999999999   -1.356171
2000-02-01 23:59:59.999999999    0.744451
2000-02-02 23:59:59.999999999    1.182222
2000-02-03 23:59:59.999999999   -0.951160
Freq: D, dtype: float64

# 11.5.4 Create PeriodIndex through an arrany

In [189]:
data = pd.read_csv("examples/macrodata.csv")

In [190]:
data

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2008,3,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
199,2008,4,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
200,2009,1,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
201,2009,2,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19
202,2009,3,12990.341,9256.0,1486.398,1044.088,10040.6,216.385,1673.9,0.12,9.6,308.013,3.56,-3.44

In [191]:
data["year"]

0      1959
1      1959
2      1959
3      1959
4      1960
       ...
198    2008
199    2008
200    2009
201    2009
202    2009
Name: year, Length: 203, dtype: int64

In [192]:
data["quarter"]

0      1
1      2
2      3
3      4
4      1
      ..
198    3
199    4
200    1
201    2
202    3
Name: quarter, Length: 203, dtype: int64

In [193]:
index = pd.PeriodIndex(year=data["year"], quarter=data["quarter"], freq="Q-DEC")

/tmp/ipykernel_3803/2492389853.py:1: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  index = pd.PeriodIndex(year=data["year"], quarter=data["quarter"], freq="Q-DEC")

In [194]:
index

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', length=203)

In [195]:
data.index = index

In [196]:
data["infl"]

1959Q1    0.00
1959Q2    2.34
1959Q3    2.74
1959Q4    0.27
1960Q1    2.31
          ...
2008Q3   -3.16
2008Q4   -8.79
2009Q1    0.94
2009Q2    3.37
2009Q3    3.56
Freq: Q-DEC, Name: infl, Length: 203, dtype: float64

# 11.6 Resampling and frequency conversion

In [197]:
dates = pd.date_range("2000-01-01", periods=100)

In [198]:
ts = pd.Series(np.random.standard_normal(len(dates)), index=dates)

In [199]:
ts

2000-01-01   -0.126102
2000-01-02    0.294882
2000-01-03    0.780681
2000-01-04   -2.122881
2000-01-05    1.225697
                ...
2000-04-05   -0.596866
2000-04-06   -0.474361
2000-04-07    1.603004
2000-04-08    0.347000
2000-04-09    1.597286
Freq: D, Length: 100, dtype: float64

In [200]:
ts.resample("M").mean()

/tmp/ipykernel_3803/3978117481.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts.resample("M").mean()

2000-01-31    0.339261
2000-02-29   -0.078206
2000-03-31    0.160753
2000-04-30    0.773637
Freq: ME, dtype: float64

In [201]:
ts.resample("M", kind="period").mean()

/tmp/ipykernel_3803/1563622178.py:1: FutureWarning: The 'kind' keyword in Series.resample is deprecated and will be removed in a future version. Explicitly cast the index to the desired type instead
  ts.resample("M", kind="period").mean()
/tmp/ipykernel_3803/1563622178.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts.resample("M", kind="period").mean()

2000-01    0.339261
2000-02   -0.078206
2000-03    0.160753
2000-04    0.773637
Freq: M, dtype: float64

# 11.6.1 Downsampling

In [202]:
dates = pd.date_range("2000-01-01", periods=12, freq="T")

/tmp/ipykernel_3803/1110584800.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  dates = pd.date_range("2000-01-01", periods=12, freq="T")

In [203]:
ts = pd.Series(np.arange(len(dates)), index=dates)

In [204]:
ts

2000-01-01 00:00:00     0
2000-01-01 00:01:00     1
2000-01-01 00:02:00     2
2000-01-01 00:03:00     3
2000-01-01 00:04:00     4
2000-01-01 00:05:00     5
2000-01-01 00:06:00     6
2000-01-01 00:07:00     7
2000-01-01 00:08:00     8
2000-01-01 00:09:00     9
2000-01-01 00:10:00    10
2000-01-01 00:11:00    11
Freq: min, dtype: int64

In [205]:
ts.resample("5min").sum()

2000-01-01 00:00:00    10
2000-01-01 00:05:00    35
2000-01-01 00:10:00    21
Freq: 5min, dtype: int64

In [206]:
ts.resample("5min", closed="right").sum()

1999-12-31 23:55:00     0
2000-01-01 00:00:00    15
2000-01-01 00:05:00    40
2000-01-01 00:10:00    11
Freq: 5min, dtype: int64

In [207]:
ts.resample("5min", closed="right", label="right").sum()

2000-01-01 00:00:00     0
2000-01-01 00:05:00    15
2000-01-01 00:10:00    40
2000-01-01 00:15:00    11
Freq: 5min, dtype: int64

In [208]:
from pandas.tseries.frequencies import to_offset

In [209]:
result = ts.resample("5min", closed="right", label="right").sum()

In [210]:
result.index = result.index + to_offset("-1s")

In [211]:
result

1999-12-31 23:59:59     0
2000-01-01 00:04:59    15
2000-01-01 00:09:59    40
2000-01-01 00:14:59    11
Freq: 5min, dtype: int64

In [212]:
ts = pd.Series(np.random.permutation(np.arange(len(dates))), index=dates)

In [213]:
ts.resample("5min").ohlc()

                     open  high  low  close
2000-01-01 00:00:00     3     9    3      9
2000-01-01 00:05:00     5    11    0      8
2000-01-01 00:10:00     1    10    1     10

# 11.6.2 Upsampling and interpolation

In [214]:
frame = pd.DataFrame(np.random.standard_normal((2, 4)),
                     index=pd.date_range("2000-01-01", periods=2, freq="W-WED"),
                     columns=["Colorado", "Texas", "New York", "Ohio"])

In [215]:
frame

            Colorado     Texas  New York      Ohio
2000-01-05 -0.304879  1.150076  0.283366 -0.581182
2000-01-12 -0.870319  0.580885  1.433157  0.843500

In [216]:
df_daily = frame.resample("D").asfreq()

In [217]:
df_daily

            Colorado     Texas  New York      Ohio
2000-01-05 -0.304879  1.150076  0.283366 -0.581182
2000-01-06       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN
2000-01-08       NaN       NaN       NaN       NaN
2000-01-09       NaN       NaN       NaN       NaN
2000-01-10       NaN       NaN       NaN       NaN
2000-01-11       NaN       NaN       NaN       NaN
2000-01-12 -0.870319  0.580885  1.433157  0.843500

In [218]:
frame.resample("D").ffill()

            Colorado     Texas  New York      Ohio
2000-01-05 -0.304879  1.150076  0.283366 -0.581182
2000-01-06 -0.304879  1.150076  0.283366 -0.581182
2000-01-07 -0.304879  1.150076  0.283366 -0.581182
2000-01-08 -0.304879  1.150076  0.283366 -0.581182
2000-01-09 -0.304879  1.150076  0.283366 -0.581182
2000-01-10 -0.304879  1.150076  0.283366 -0.581182
2000-01-11 -0.304879  1.150076  0.283366 -0.581182
2000-01-12 -0.870319  0.580885  1.433157  0.843500

In [219]:
frame.resample("D").ffill(limit=2)

            Colorado     Texas  New York      Ohio
2000-01-05 -0.304879  1.150076  0.283366 -0.581182
2000-01-06 -0.304879  1.150076  0.283366 -0.581182
2000-01-07 -0.304879  1.150076  0.283366 -0.581182
2000-01-08       NaN       NaN       NaN       NaN
2000-01-09       NaN       NaN       NaN       NaN
2000-01-10       NaN       NaN       NaN       NaN
2000-01-11       NaN       NaN       NaN       NaN
2000-01-12 -0.870319  0.580885  1.433157  0.843500

In [220]:
frame.resample("W-THU").ffill()

            Colorado     Texas  New York      Ohio
2000-01-06 -0.304879  1.150076  0.283366 -0.581182
2000-01-13 -0.870319  0.580885  1.433157  0.843500

In [221]:
frame

            Colorado     Texas  New York      Ohio
2000-01-05 -0.304879  1.150076  0.283366 -0.581182
2000-01-12 -0.870319  0.580885  1.433157  0.843500

# 11.6.3 Resampling base on usage period

In [222]:
frame = pd.DataFrame(np.random.standard_normal((24, 4)),
                     index=pd.period_range("1-2000", "12-2001", freq="M"),
                     columns=["Colorado", "Texas", "New York", "Ohio"])

In [223]:
frame.head()

         Colorado     Texas  New York      Ohio
2000-01  0.333199  0.037982  0.277130  1.706488
2000-02  0.295721 -0.436448  0.159202 -0.196782
2000-03  1.404427 -0.219272  0.633641  1.363800
2000-04 -1.326863  0.577875 -1.327662  1.455564
2000-05 -1.066137  2.038474  0.707125 -0.314252

In [224]:
annual_frame = frame.resample("A-DEC").mean()

/tmp/ipykernel_3803/468843495.py:1: FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
  annual_frame = frame.resample("A-DEC").mean()

In [225]:
annual_frame

      Colorado     Texas  New York      Ohio
2000 -0.246581  0.117022  0.139854  0.384661
2001 -0.135319 -0.311507 -0.249865 -0.449357

In [226]:
annual_frame.resample("Q-DEC").ffill()

        Colorado     Texas  New York      Ohio
2000Q1 -0.246581  0.117022  0.139854  0.384661
2000Q2 -0.246581  0.117022  0.139854  0.384661
2000Q3 -0.246581  0.117022  0.139854  0.384661
2000Q4 -0.246581  0.117022  0.139854  0.384661
2001Q1 -0.135319 -0.311507 -0.249865 -0.449357
2001Q2 -0.135319 -0.311507 -0.249865 -0.449357
2001Q3 -0.135319 -0.311507 -0.249865 -0.449357
2001Q4 -0.135319 -0.311507 -0.249865 -0.449357

In [227]:
annual_frame.resample("Q-DEC", convention="end").asfreq()

        Colorado     Texas  New York      Ohio
2000Q4 -0.246581  0.117022  0.139854  0.384661
2001Q1       NaN       NaN       NaN       NaN
2001Q2       NaN       NaN       NaN       NaN
2001Q3       NaN       NaN       NaN       NaN
2001Q4 -0.135319 -0.311507 -0.249865 -0.449357

In [228]:
annual_frame.resample("Q-MAR").ffill()

        Colorado     Texas  New York      Ohio
2000Q4 -0.246581  0.117022  0.139854  0.384661
2001Q1 -0.246581  0.117022  0.139854  0.384661
2001Q2 -0.246581  0.117022  0.139854  0.384661
2001Q3 -0.246581  0.117022  0.139854  0.384661
2001Q4 -0.135319 -0.311507 -0.249865 -0.449357
2002Q1 -0.135319 -0.311507 -0.249865 -0.449357
2002Q2 -0.135319 -0.311507 -0.249865 -0.449357
2002Q3 -0.135319 -0.311507 -0.249865 -0.449357

# 11.6.4 Resample the grouping time

In [229]:
N = 15

In [230]:
times = pd.date_range("2017-05-20 00:00", freq="1min", periods=N)

In [231]:
df = pd.DataFrame({"time": times,
                   "value": np.arange(N)})

In [232]:
df

                  time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [233]:
df.set_index("time").resample("5min").count()

                     value
time
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [234]:
df2 = pd.DataFrame({"time": times.repeat(3),
                    "key": np.tile(["a", "b", "c"], N),
                    "value": np.arange(N * 3.)})

In [235]:
df2.head(7)

                 time key  value
0 2017-05-20 00:00:00   a    0.0
1 2017-05-20 00:00:00   b    1.0
2 2017-05-20 00:00:00   c    2.0
3 2017-05-20 00:01:00   a    3.0
4 2017-05-20 00:01:00   b    4.0
5 2017-05-20 00:01:00   c    5.0
6 2017-05-20 00:02:00   a    6.0

In [236]:
time_key = pd.Grouper(freq="5min")

In [239]:
resampled = (df2.set_index("time").groupby(["key", time_key]).sum())

In [240]:
resampled

                         value
key time
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [242]:
resampled.reset_index()

  key                time  value
0   a 2017-05-20 00:00:00   30.0
1   a 2017-05-20 00:05:00  105.0
2   a 2017-05-20 00:10:00  180.0
3   b 2017-05-20 00:00:00   35.0
4   b 2017-05-20 00:05:00  110.0
5   b 2017-05-20 00:10:00  185.0
6   c 2017-05-20 00:00:00   40.0
7   c 2017-05-20 00:05:00  115.0
8   c 2017-05-20 00:10:00  190.0

# 11.7 Move Window Function